{% set name = "statannotations" %}
{% set version = "0.7.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/statannotations-{{ version }}.tar.gz
  sha256: a93e428682d66c9fca5a399d5bd3fe7c9cef0500f53840c6f5362526b4501e93

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - numpy >=1.12.1
    - seaborn >=0.9.0
    - matplotlib-base >=2.2.2
    - pandas >=0.23.0,<3.0
    - scipy >=1.1.0
    - statsmodels
    - packaging

test:
  imports:
    - statannotations
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/trevismd/statannotations
  summary: add statistical significance or custom annotations on seaborn plots. Based on statannot 0.2.3
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mbhall88
    - trevismd
